### ISSUE TITLE
Derive.makeFunctor has disappeared

### ISSUE THREAD

**Issue by jkoppel** [pa-ba/compdata#23]
[50 of 62] Compiling Data.Comp.Derive ( src/Data/Comp/Derive.hs, dist/build/Data/Comp/Derive.o )

src/Data/Comp/Derive.hs:73:24: Not in scope: ‘A.makeFunctor’

This wouldn't be such a large problem, except that I failed to install an old derive, because it requires an old mtl. Use deriving Functor instead, maybe?

**Comment by pa-ba** [comment]
Thanks for reporting the issue. I removed the makeFunctor function. As you suggested, the recommendation is to use the DeriveFunctor extension instead. I'll upload the new version to hackage shortly.
