### ISSUE TITLE
Put compdata in stackage again

### ISSUE THREAD

**Issue by flip111** [pa-ba/compdata#32]
Hey thanks for this library. I saw that it used to be on stackage, unfortunately it's not longer there in the latest LTS. Could it be put back? https://www.stackage.org/lts-16.19/hoogle?q=compdata

**Comment by pa-ba** [comment]
The dependency on `tree-view`, which is not on Stackage, blocks this at the moment.

**Comment by flip111** [comment]
In what order would be your preference between these choices?

1. get rid of the functionality tree-view provides
2. put tree-view on stackage
3. replace tree-view with another package that does the same
4. write code to replace tree-view

what for does compdata use tree-view ?

**Comment by emilaxelsson** [comment]
The `tree-view` rendering was added by me, and I'm also the `tree-view` maintainer. Putting `tree-view` on Stackage looks like it should be straightforward given that it has minimal dependencies. I'll give that a shot today.

**Comment by emilaxelsson** [comment]
Here's the PR to add `tree-view` to Stackage: https://github.com/commercialhaskell/stackage/pull/5855

**Comment by emilaxelsson** [comment]
> Here's the PR to add `tree-view` to Stackage: [commercialhaskell/stackage#5855](https://github.com/commercialhaskell/stackage/pull/5855)

Now merged.

**Comment by pa-ba** [comment]
Thanks @emilaxelsson!

I filed a PR to add compdata to stackage: https://github.com/commercialhaskell/stackage/pull/5857

**Comment by pa-ba** [comment]
PR to add compdata to stackage has been merged: https://github.com/commercialhaskell/stackage/pull/5857
